### ISSUE TITLE
GIF from the project?

### ISSUE THREAD

**Issue by EralpB** [AbhimanyuForiOS/GoogleNewsStandAnimation#6]
Quick question to make sure, if GIF really taken from the project?
or is it just an example?

**Comment by AbhimanyuForiOS** [comment]
This is an example and gif created by designer. We made the same animation effect  in iOS Swift 3 Programming  language.
you can download the code and run the program or if you want to more realtime then you can check following link-

https://www.cocoacontrols.com/controls/googlenewsstandanimation
